dubbo:
  application:
    logger: slf4j
    name: BaseApplication
  registry:
    address: nacos://${NACOS_HOST:localhost}:${NACOS_PORT:8848}
  config-center:
    address: nacos://${NACOS_HOST:localhost}:${NACOS_PORT:8848}
  protocol:
    name: tri
    port: 50051
