dubbo:
  application:
    logger: slf4j
    name: BaseApplication
  registry:
    address: nacos://${NACOS_HOST:localhost}:${NACOS_PORT:8848}
  config-center:
    address: nacos://${NACOS_HOST:localhost}:${NACOS_PORT:8848}
  protocol:
    name: tri
    port: 50051

sa-token:
  alone-redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    username: ${REDIS_USERNAME:}
    password: ${REDIS_PASSWORD:}

lab:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    username: ${REDIS_USERNAME:}
    password: ${REDIS_PASSWORD:}
    key-prefix: lab
