spring:
  application:
    name: rule-engine

  datasource:
    url: jdbc:mysql://localhost:3306/lab_sys?useUnicode=true&characterEncoding=utf-8
    username: root
    password: sbx159357!?.

server:
  port: 3334

dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 4444
  provider:
    timeout: 5_000

